<?php
$livros = [
    ['id' => 1, 'titulo' => 'Senhor dos Anéis', 'autor' => 'J.R.R Tolkien', 'descricao' => 'A história de O Senhor dos Anéis ocorre num tempo e espaço imaginário, a Terceira Era da Terra Média, que é um mundo inspirado na Terra real, mais especificamente, segundo Tolkien, numa Europa mitológica, habitado por Humanos e por outras raças: Elfos, Anãos (anteriormente "Anões"), Hobbits e Orques (anteriormente "Orcs").'],
    ['id' => 2, 'titulo' => 'Star Wars', 'autor' => 'George Lucas', 'descricao' => 'A franquia Star Wars retrata as aventuras de personagens "há muito tempo em uma galáxia muito, muito distante" em várias eras fictícias , nas quais humanos e muitas espécies de alienígenas (frequentemente humanoides ) coexistem com dróides , que podem ser programados para assistência pessoal ou batalha. Viagens espaciais entre planetas são comuns devido à tecnologia do hiperespaço de velocidade da luz.'],
    ['id' => 3, 'titulo' => 'Dune', 'autor' => 'Frank Herbert', 'descricao' => 'Duna se passa em um futuro distante no meio de um império intergaláctico feudal em expansão, onde feudos planetários são controlados por Casas nobres que devem aliança à casta imperial da Casa Corrino. O livro conta a história do jovem Paul Atreides, herdeiro do Duque Leto Atreides e da respectiva Casa Atreides, na ocasião da transferência de sua família para o planeta Arrakis, a única fonte no universo da especiaria melange.'],
    ['id' => 4, 'titulo' => 'Harry Potter', 'autor' => 'J.K Rowling', 'descricao' => 'Harry Potter é uma série de sete romances de fantasia escrita pela autora britânica J. K. Rowling. A série narra as aventuras de um jovem chamado Harry James Potter (Harry Tiago Potter, no Brasil), que descobre aos 11 anos de idade que é um bruxo ao ser convidado para estudar na Escola de Magia e Bruxaria de Hogwarts.'],
    ['id' => 5, 'titulo' => 'Assasins Creed Renascença', 'autor' => 'Oliver Bowden', 'descricao' => 'Assassins Creed: Renascença (livro) é o primeiro livro baseado na série Assassins Creed, escrito por Oliver Bowden e publicado pela Penguin Books, em janeiro de 2009. Trata-se de uma versão literária do jogo Assassins Creed II mas, em vez de estender por um bom período de tempo o livro passa-se somente no século XV, sem menção ao eventos do presente do jogo.'],
    ['id' => 6, 'titulo' => 'Naruto', 'autor' => 'Masashi Kishimoto', 'descricao' => 'O mangá Naruto foi escrito e ilustrado por Masashi Kishimoto, e foi publicado pela editora Shueisha na revista Weekly Shōnen Jump.[1] O primeiro capítulo do Naruto foi publicado em novembro de 1999 e a publicação encerrou em novembro de 2014 no capítulo 700, contando com 72 volumes, mais um volume extra, com capítulos lançados posteriormente.'],
    ['id' => 7, 'titulo' => 'Dragon Ball Z', 'autor' => 'Akira Toryama', 'descricao' => 'Cinco anos depois do final da série anterior, Son Goku já é adulto e tem seu filho Son Gohan, fruto de seu casamento com Chi-Chi. Um homem desconhecido chamado Raditz chega à Terra em uma nave espacial e encontra Goku, contando que é seu irmão mais velho e que seu verdadeiro nome é Kakarotto, informando também que os dois são membros de uma raça guerreira quase extinta chamada Saiyajins.'],
    ['id' => 8, 'titulo' => 'One Piece', 'autor' => 'Eiichiro Oda', 'descricao' => 'O mundo de One Piece é povoado por humanos e muitas outras raças, como anões, homens-peixe e gigantes. É coberto por dois vastos oceanos, que são divididos por uma enorme cordilheira chamada Red Line; A Grand Line, um mar que corre perpendicularmente à Red Line, divide-os em quatro mares: North Blue, East Blue, West Blue e South Blue.']
];
